B-20564: Email for Missing Data
transcom/trdm-lambda pull request #17
Opened 2024-07-23 17:30 UTC by TevinAdams

Added logic to send an email when malformed TAC and LOA data is being skipped during parsing. Currently in an email I am just sending the TAC and LOA sys Id and can easily add on more information. Need to find a way to test this in staging where the actual email can be sent. Once tested i will also update the email sender, recipient, subject, and body as needed. Those are only HTML edits. Need to make sure email is actually going to be sent and received after this first round of implementation. Added logging to help a quick debug.

2024-07-23 21:38 UTC, traskowskycaci requested changes
Overall looks good! Left a few comments

2024-07-23 21:38 UTC, traskowskycaci commented on src/main/java/com/milmove/trdmlambda/milmove/service/EmailService.java
> +    //
Empty comment here

2024-07-23 21:38 UTC, traskowskycaci commented on src/main/java/com/milmove/trdmlambda/milmove/service/EmailService.java
> +                .data(this.bodyHTML)
On line 89/90, content = this.bodyHTML but on line 97/98, the body = html(content). Are these switched around, should body = body and content = content?

2024-07-23 21:38 UTC, traskowskycaci commented on src/main/java/com/milmove/trdmlambda/milmove/service/EmailService.java
> +                .html(content)
On line 89/90, content = this.bodyHTML but on line 97/98, the body = html(content). Are these switched around, should body = body and content = content?

2024-07-24 14:16 UTC, TevinAdams commented on src/main/java/com/milmove/trdmlambda/milmove/service/EmailService.java
> +                .data(this.bodyHTML)
@traskowskycaci  No. The Body.builder().HTML() takes type Content as a param. Where as Content.builder().data() takes param type of String. In this case the string is html. Then that Content object is used to build the Body object.

2024-07-24 14:17 UTC, traskowskycaci commented on src/main/java/com/milmove/trdmlambda/milmove/service/EmailService.java
> +                .data(this.bodyHTML)
I see. Thanks for the explanation!

2024-07-24 14:17 UTC, TevinAdams commented on src/main/java/com/milmove/trdmlambda/milmove/service/EmailService.java
> +    //
Removed empty comment

2024-07-24 14:18 UTC, TevinAdams commented on src/main/java/com/milmove/trdmlambda/milmove/service/EmailService.java
> +                .html(content)
@traskowskycaci No. The Body.builder().HTML() takes type Content as a param. Where as Content.builder().data() takes param type of String. In this case the string is html. Then that Content object is used to build the Body object.

2024-07-24 14:18 UTC, traskowskycaci approved these changes

2024-07-24 16:40 UTC, merged