B-20564: Malformed Data Notification
transcom/trdm-lambda pull request #26
Opened 2024-09-16 22:07 UTC by TevinAdams

Ticket: [B-20564](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-20564)

This PR introduces new functionality such as:

1. SNS notification that sends an email to "Milmove-Developers" when malformed TAC and LOA data is detected while parsing the pipe delimited file of TGET data
3. TRDM Truststore file is now stored in S3, and is now being retrieved

Testing was done in the STG env with assistance from the Brightstars team.

- Screenshot of a successful request to AWS SNS to send a Malformed LOA message
![SNS LOA Log](https://github.com/user-attachments/assets/48c956d7-ad80-4d1d-b0fb-9bdaeef02f35)

- Screenshot of a successful request to AWS SNS to send a Malformed TAC message
![SNS TAC Log](https://github.com/user-attachments/assets/5e4aa6d0-7605-458e-8567-5831506eb606)

- Screenshot of a successful request to retrieve TRDMs truststore from S3
![S3 Truststore Fetch Log](https://github.com/user-attachments/assets/11beecb4-48fe-400e-bb18-4df8c1135248)

- Screenshot of the keystore being successfully built and configured after fetching TRDMs truststore form S3
![Keystore configured Log](https://github.com/user-attachments/assets/5a60857e-f6cc-4622-aa66-c4532851f3c2)

2024-09-17 14:52 UTC, TevinAdams commented
Corrected typos in the description.

2024-09-18 15:55 UTC, cameroncaci requested changes
Needs a version bump

2024-09-18 15:55 UTC, cameroncaci commented on src/main/java/com/milmove/trdmlambda/milmove/service/SNSService.java
> +    }
Recommending combining these two funcs as they're identify minus the param of "TAC" or "LOA" which can be a param

2024-09-18 16:55 UTC, TevinAdams commented on src/main/java/com/milmove/trdmlambda/milmove/service/SNSService.java
> +    }
@cameroncaci  Just refactored to remove repetitive code

2024-09-18 16:55 UTC, TevinAdams commented
> Corrected typos in the description.

@cameroncaci  Done

2024-09-18 17:09 UTC, traskowskycaci reviewed
Some changes in src/main/java/com/milmove/trdmlambda/milmove/util/Trdm.java were just spacing diffs where one line became two. Just curious why that spacing was changed?

2024-09-18 17:17 UTC, TevinAdams commented
> Some changes in src/main/java/com/milmove/trdmlambda/milmove/util/Trdm.java were just spacing diffs where one line became two. Just curious why that spacing was changed?

@traskowskycaci I format all the files I touch with Java Redhat formatter

2024-09-18 17:19 UTC, traskowskycaci commented
> > Some changes in src/main/java/com/milmove/trdmlambda/milmove/util/Trdm.java were just spacing diffs where one line became two. Just curious why that spacing was changed?
> 
> @traskowskycaci I format all the files I touch with Java Redhat formatter

Sounds good, I wondered if that was the case. Thanks for the explanation!

2024-09-18 17:19 UTC, traskowskycaci approved these changes
Makes sense to me overall, and I have seen those emails coming in as further proof. Looks good!

2024-09-20 14:54 UTC, cameroncaci approved these changes

2024-09-20 16:56 UTC, merged