B-19842: Duplicate data protection – Allow updating – Wrap in Transaction
transcom/trdm-lambda pull request #9
Opened 2024-05-31 19:39 UTC by TevinAdams

In this PR the following functionality is introduced:

1. Duplicate Loas are removed before any update or inserts- Any Loa that has a non-unique loa_sys_id, and its Id is not used in TAC db table loa_id column is deleted
2. Loa updates - If a loa exist with the same loa_sys_id then the load is updated with the incoming one instead of a new insert
3. TAC updates - If there is a TAC code that already exist with the same tac_sys_id as the incoming one then the current TAC is updated instead of a new insert
4. On TAC and LOA updates rollback is being used. If one query fail in the batch the connection will rollback any changes that were made
5. Additional logging was added. TAC and LOA Ids are logged when updates occur.

# TESTING
Need to be able to run the unit tests to test these changes

2024-06-03 14:39 UTC, deandreJones approved these changes

2024-06-03 16:22 UTC, cameroncaci requested changes
Requesting version bump in `pom.xml`

2024-06-05 19:24 UTC, TevinAdams commented on src/main/java/com/milmove/trdmlambda/milmove/util/Trdm.java
> +                        List<LineOfAccounting> createLoas = identifyLoasToCreate(loas, updateLoas);
Fixed

2024-06-05 19:26 UTC, TevinAdams commented on src/main/java/com/milmove/trdmlambda/milmove/util/Trdm.java
> +    }
@cameroncaci  What do you mean? I need this uncommented.

2024-06-05 19:29 UTC, TevinAdams commented
> Requesting version bump in `pom.xml`



> Requesting version bump in `pom.xml`

Acknowledged

2024-06-05 19:34 UTC, TevinAdams commented on src/main/java/com/milmove/trdmlambda/milmove/service/DatabaseService.java
> +        String sql = "Delete From lines_of_accounting Where id in (Select id From lines_of_accounting Where loa_sys_id in (SELECT loa_sys_id FROM lines_of_accounting GROUP BY loa_sys_id HAVING COUNT(
@cameroncaci  Okay let me see what I can whip up

2024-06-06 19:00 UTC, traskowskycaci commented
Holding off on reviewing this for now as Tevin has some in-progress work

2024-06-07 15:06 UTC, cameroncaci commented on src/main/java/com/milmove/trdmlambda/milmove/util/Trdm.java
> +    }
@TevinAdams 
Oh no, I meant like there are no comments above the function explaining what they do, like how the TAC funcs have comments

2024-06-07 17:51 UTC, TevinAdams commented on src/main/java/com/milmove/trdmlambda/milmove/service/DatabaseService.java
> +        String sql = "Delete From lines_of_accounting Where id in (Select id From lines_of_accounting Where loa_sys_id in (SELECT loa_sys_id FROM lines_of_accounting GROUP BY loa_sys_id HAVING COUNT(
@cameroncaci  Just finished changing the entire delete functionality. Now we recognize the loas to delete based on the following:

1. Is the loa loa_sys_id unique if not then
2. Is the loa referenced in any TAC loa_id if not then
3. Amongst other loas that have the same loa_sys_id and not referenced in TAC add the one with the latest created_at date to a list of loas to be deleted

That list is then passed to a function that simply deletes a list of loas.

2024-06-07 18:50 UTC, TevinAdams commented on src/main/java/com/milmove/trdmlambda/milmove/util/Trdm.java
> +    }
@cameroncaci Added comments. Sorry if any of this doesn't make sense i feel like its a lot to explain.

2024-06-10 14:21 UTC, danieljordan-caci requested changes
Just some spelling oopsies

2024-06-10 17:27 UTC, TevinAdams commented on src/main/java/com/milmove/trdmlambda/milmove/util/Trdm.java
> +        logger.info("finished identfying duplicate Line of Accounting codes to delete");
@danieljordan-caci  Fixed.

2024-06-10 17:27 UTC, TevinAdams commented on src/main/java/com/milmove/trdmlambda/milmove/util/Trdm.java
> +            // If already confimred a duplicate then no need to check if it is
@danieljordan-caci  Fixed

2024-06-10 17:27 UTC, TevinAdams commented on src/main/java/com/milmove/trdmlambda/milmove/util/Trdm.java
> +                // Identify Loas to delete based on if their loaSysId is not unique, their id/primary key is not refeenced in TACS loa_id and the loa is the latest
@deandreJones  fixed

2024-06-12 14:46 UTC, merged